// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Second.DataAccess.ApplicationDb
{
    public partial class Horse
    {
        public Horse()
        {
            InverseDam = new HashSet<Horse>();
            InverseSire = new HashSet<Horse>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public byte ColorId { get; set; }
        public int? SireId { get; set; }
        public int? DamId { get; set; }
        public int RaceStarts { get; set; }
        public int RaceWins { get; set; }
        public int RacePlace { get; set; }
        public int RaceShow { get; set; }
        public int Earnings { get; set; }

        public virtual Color Color { get; set; }
        public virtual Horse Dam { get; set; }
        public virtual Horse Sire { get; set; }
        public virtual ICollection<Horse> InverseDam { get; set; }
        public virtual ICollection<Horse> InverseSire { get; set; }
    }
}